import Head from 'next/head'
import Image from 'next/image'
import Footer from '../componets/footer'
import Header from '../componets/header'
import Headline from '../componets/headline'
import Links from '../componets/links'
import Main from '../componets/main'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main page="about" />

      <Footer />
    </div>
  )
}
