import Head from 'next/head'
import Footer from '../componets/footer'
import Header from '../componets/header'
import Main from '../componets/main'
import styles from '../styles/Home.module.css'
import React, { useState, useEffect, useCallback } from 'react';
import { useCounter } from '../hooks/useCounter';
import { useInputText } from '../hooks/useInputText';

export default function Home() {

  const {count, handleClick} = useCounter();

  const {text, isShow, array, handleText, handleIsShow, handleAdd} = useInputText();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header /> 
      <div className={styles.center}>
        <h2>{count}</h2>
        <button onClick={handleClick}>加1</button>
        <br />
        <button onClick={handleIsShow}>顯示</button>
        <br />
        {isShow ? <input type="input" value={text} onChange={handleText} /> : null}
        <br />
        <button onClick={handleAdd}>加入</button>
        <br />
        <ul>
          {array.map((item, index) => {
            return <li key={index}>{item}</li>
          })}
        </ul>
      </div>
      <Main page="index" />
      <Footer />
    </div>
  )
}